### ISSUE TITLE
Archivy Roadmap

### ISSUE THREAD

**Issue by Uzay-G** [Uzay-G/archivy#74]
These are features we're exploring for the release of Archivy 1.0:

- Frontend UI for editing
- Expand data store so users can highlight / annotate content with a nice experience even on mobile
- Login modules so users can access and edit from a remote server
- pdf import + epub

What do you think are important focuses for Archivy that could be interesting to develop? Please share!

**Comment by HarshaVardhanJ** [comment]
Login could be handled by either Apache or Nginx as a frontend proxy for authentication. I think it is better to delegate authentication to a web server which will act as a proxy. In any case, when Archivy is deployed as a container, there's generally a proxy deployed for authentication. Thoughts?

**Comment by HarshaVardhanJ** [comment]
@Uzay-G @srevinsaju @clemux Regarding Docker images, how many versions of Archivy do you think should be maintained? Right now, I'm maintaining only the most recent version. I'm guessing once the application reaches a certain level of stability and maturity in terms of feature set, we could provide images of the last 3 or 4 stable versions. Thoughts?

**Comment by srevinsaju** [comment]
I would like to have this, and considering other open source docker images, they maintain:
* `archivy:latest` : latest stable release
* `archivy:beta`: latest pre release 
* `archivy:continuous`: upto date with master (can use Continuous Integration to automatically create docker images and publish them)
* `archivy:*.*` Fixed tag. Once released, no more changes should be made to the existing tag

**Comment by HarshaVardhanJ** [comment]
That looks good. We could tag the images based on semantic versioning. How many major releases do we maintain?

**Comment by nandantumu** [comment]
Sometimes webpage formatting can have an impact on the way the content looks. Maybe a more robust webpage capture could be on the roadmap? Something like this: [HTTrack](https://www.httrack.com/)

**Comment by Uzay-G** [comment]
Hmm definitely something to look into. I'd like to find a tradeoff between simplicity and speed and the quality of the formatting.

**Comment by Uzay-G** [comment]
## Roadmap for future versions

This is only a **draft**, and ideas or suggestions are welcome.

## v2.0

* [ ] More lightweight and simple search alternative #13
* [ ] Security Improvements:
   * [ ] Rate limiting
   * [ ] Think about password validation
   * [ ] Email recovery
* [ ] More full-featured distribution methods (mobile, desktop, etc...)
* [ ] Develop archival process #169
* [ ] Possible improvements on customization, for example related to the UI
* [ ] Polish web interface for CLI
* [ ] Add to tag functionality #168 
* [ ] Highlighting / annotations #97
* [ ] More customization of settings, for example whether or not non-logged in users can access content.

## v3.0

* [ ] Federation
* [ ] Provide standalone binary releases (no python needed) to make server deployment easy
* [ ] Encrypted share link (expires within n days, password-protected, link only shares)
* [ ] Multi-User
* [ ] SMTP / IMAP support, verify users by email address, invite users by email address, invite by link.

**Comment by dstar4138** [comment]
Minor suggestion for the v3.0 milestones; you may be able to leverage something like [Authelia](https://www.authelia.com/)?

**Comment by Uzay-G** [comment]
It looks nice, but would probably be too big of a dependency / setup for self-hosting archivy.

**Comment by mrmaxguns** [comment]
Image uploads would be an awesome feature :+1: Editing tags would be awesome; so would the ability to internally link between the files.

**Comment by mrmaxguns** [comment]
I bodged together a short shell script to deal with images and to run archivy locally, while image uploads aren't implemented:

```sh
set -m
echo Starting Elasticsearch
sudo service elasticsearch start
sudo service elasticsearch status
echo Running archivy and python image server
archivy run & python3 -m http.server --directory /home/maxim/ArchivyImageContent 5050 && fg
echo Exit
```

(Assuming all images are at `ArchivyImageContent`)

**Comment by Uzay-G** [comment]
Ok internal links and a search engine alternative are implemented in the last release :).

Image upload would definitely be nice :thinking:

**Comment by Uzay-G** [comment]
@mrmaxguns I wrote some code to get image upload working, could you maybe test it out :smile:. You can clone the branch from this PR -> https://github.com/archivy/archivy/pull/224.

That'd be really awesome, and if everything works I'll go ahead and merge it + make a new release :)

**Comment by mrmaxguns** [comment]
@Uzay-G Yes, I am willing to test it out. I'll comment on the PR after testing it out.

**Comment by Uzay-G** [comment]
Perfect! Thanks :)

**Comment by Uzay-G** [comment]
Image upload, links between notes, and embedded tags inside notes, of the form: "I love #archivy#", are now all in Archivy core.

**Comment by andrewchenshx** [comment]
1)Section Editing: allows editing of small parts of a page
2)Automatic table of contents generation
thanks 👍

**Comment by Uzay-G** [comment]
What do you mean by automatic table of contents generation? doesn't archivy also do that?

How would you want the section editing to work.

**Comment by andrewchenshx** [comment]
> What do you mean by automatic table of contents generation? doesn't archivy also do that?
better make the toc box float at the top right corner of the content(even when the user scroll down the lengthy page). This allows users to have a quick look at the page structure and quickly jump to the part of the page they want. 
> How would you want the section editing to work?
Each headline (usually only the first 3 levels) starts a new section. When a page is writable a small Edit button appears at the end of the section. Using this button loads only this section into the editor. 
cheers :)

**Comment by Uzay-G** [comment]
Big goals:

- improve ease of use (mobile? desktop app? hosted service?)
- improve ripgrep search
- implement automatic mechanisms for discovery (cf [Espial](https://github.com/Uzay-G/espial))
- federation?
- UI plugins

**Comment by Uzay-G** [comment]
@andrewchenshx I haven't forgotten you! My specialty just isn't UI stuff but I need to get to it.
